# Generated by Django 3.0.7 on 2020-08-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cmail', models.EmailField(max_length=100)),
                ('cmsg', models.TextField(max_length=500)),
            ],
        ),
    ]
